// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKmqyiSwdxU2nZYw2lpH6fjEMdGam6g0M',
    appId: '1:485013512985:web:1312bc2b24c2159f569b88',
    messagingSenderId: '485013512985',
    projectId: 'apt-app-d09ef',
    authDomain: 'apt-app-d09ef.firebaseapp.com',
    storageBucket: 'apt-app-d09ef.firebasestorage.app',
    measurementId: 'G-NWSMY32RX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx2NnG9noFjiUmgxTJm2mWsDWf6WAx09k',
    appId: '1:485013512985:android:c3885058927c43a5569b88',
    messagingSenderId: '485013512985',
    projectId: 'apt-app-d09ef',
    storageBucket: 'apt-app-d09ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArA9bHB8_kCDzIGk7zmVTcNSUfXrpVSUk',
    appId: '1:485013512985:ios:ecefc7acb744220e569b88',
    messagingSenderId: '485013512985',
    projectId: 'apt-app-d09ef',
    storageBucket: 'apt-app-d09ef.firebasestorage.app',
    iosBundleId: 'com.example.apt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArA9bHB8_kCDzIGk7zmVTcNSUfXrpVSUk',
    appId: '1:485013512985:ios:ecefc7acb744220e569b88',
    messagingSenderId: '485013512985',
    projectId: 'apt-app-d09ef',
    storageBucket: 'apt-app-d09ef.firebasestorage.app',
    iosBundleId: 'com.example.apt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKmqyiSwdxU2nZYw2lpH6fjEMdGam6g0M',
    appId: '1:485013512985:web:47d9a709975d1f91569b88',
    messagingSenderId: '485013512985',
    projectId: 'apt-app-d09ef',
    authDomain: 'apt-app-d09ef.firebaseapp.com',
    storageBucket: 'apt-app-d09ef.firebasestorage.app',
    measurementId: 'G-R042W8WS0F',
  );

}